import { SIGNS } from './data.js';
const norm=n=>((n%360)+360)%360,rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI;
export function signFromLongitude(longitude){const x=norm(longitude),i=Math.floor(x/30);return {...SIGNS[i],degree:x%30};}
export function sunSignFromDate(month,day){const md=month*100+day;if(md>=321&&md<=419)return {...SIGNS[0]};if(md>=420&&md<=520)return {...SIGNS[1]};if(md>=521&&md<=620)return {...SIGNS[2]};if(md>=621&&md<=722)return {...SIGNS[3]};if(md>=723&&md<=822)return {...SIGNS[4]};if(md>=823&&md<=922)return {...SIGNS[5]};if(md>=923&&md<=1022)return {...SIGNS[6]};if(md>=1023&&md<=1121)return {...SIGNS[7]};if(md>=1122&&md<=1221)return {...SIGNS[8]};if(md>=1222||md<=119)return {...SIGNS[9]};if(md>=120&&md<=218)return {...SIGNS[10]};return {...SIGNS[11]};}
export function julianDay(date){return date.getTime()/86400000+2440587.5;}
export function sunLongitude(jd){const T=(jd-2451545)/36525,L0=norm(280.46646+36000.76983*T),M=norm(357.52911+35999.05029*T),C=(1.914602-0.004817*T)*Math.sin(rad(M))+0.019993*Math.sin(rad(2*M))+0.000289*Math.sin(rad(3*M));return norm(L0+C);}
export function moonLongitude(jd){const d=jd-2451543.5,N=norm(125.1228-0.0529538083*d),i=5.1454,w=norm(318.0634+0.1643573223*d),e=.0549,M=norm(115.3654+13.0649929509*d),E=M+deg(e*Math.sin(rad(M))*(1+e*Math.cos(rad(M)))),x=60.2666*(Math.cos(rad(E))-e),y=60.2666*Math.sqrt(1-e*e)*Math.sin(rad(E)),r=Math.hypot(x,y),v=deg(Math.atan2(y,x)),lon=norm(v+w),xe=r*(Math.cos(rad(N))*Math.cos(rad(lon))-Math.sin(rad(N))*Math.sin(rad(lon))*Math.cos(rad(i))),ye=r*(Math.sin(rad(N))*Math.cos(rad(lon))+Math.cos(rad(N))*Math.sin(rad(lon))*Math.cos(rad(i)));return norm(deg(Math.atan2(ye,xe)));}
function gst(jd){const T=(jd-2451545)/36525;return norm(280.46061837+360.98564736629*(jd-2451545)+0.000387933*T*T);}
export function ascendantLongitude(jd,lat,lon){const T=(jd-2451545)/36525,e=rad(23.439291-0.0130042*T),theta=rad(norm(gst(jd)+lon)),phi=rad(lat),lambda=Math.atan2(-Math.cos(theta),Math.sin(theta)*Math.cos(e)+Math.tan(phi)*Math.sin(e));return norm(deg(lambda)+180);}
function partsInTimeZone(date,timeZone){const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(parts.filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));}
export function zonedLocalToUtc(dateString,timeString,timeZone){const [y,m,d]=dateString.split('-').map(Number),[h,min]=timeString.split(':').map(Number),target=Date.UTC(y,m-1,d,h,min);let guess=target;for(let i=0;i<3;i++){const p=partsInTimeZone(new Date(guess),timeZone),represented=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);guess+=target-represented;}return new Date(guess);}
export async function geocodePlace(place,timeoutMs=7000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const url=`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(place)}&count=1&language=fr&format=json`,response=await fetch(url,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error('Service de localisation indisponible.');const data=await response.json();if(!data.results?.length)throw new Error('Lieu introuvable. Essayez « ville, pays ».');return data.results[0];}catch(error){if(error?.name==='AbortError')throw new Error('La recherche du lieu a pris trop de temps. Le portrait peut être généré sans Ascendant.');throw error;}finally{clearTimeout(timer);}}
export function moonSignWithoutTimezone(dateString,timeString){const [y,m,d]=dateString.split('-').map(Number),[h,min]=timeString.split(':').map(Number),names=new Set();for(let offset=-12;offset<=14;offset+=2){const utc=new Date(Date.UTC(y,m-1,d,h-offset,min));names.add(signFromLongitude(moonLongitude(julianDay(utc))).name);if(names.size>1)return null;}const name=[...names][0];return SIGNS.find(s=>s.name===name)||null;}
export function formatSign(sign){if(!sign)return '—';return sign.degree===undefined?sign.name:`${sign.name} · ${sign.degree.toFixed(1)}°`;}
