import { signFromLongitude, sunSignFromDate, julianDay, sunLongitude, moonLongitude, ascendantLongitude, zonedLocalToUtc, geocodePlace, moonSignWithoutTimezone } from './astro.js';
import { chineseYearProfile, chineseHourAnimal } from './chinese.js';
import { buildContent } from './content.js';
import { renderProfile, setLoading, setStatus, setupStaticInteractions } from './render.js';
import { setupPdfExport } from './pdf.js';
const state={profile:null,content:null};window.TADAMB_STATE=state;const value=id=>document.querySelector(id)?.value?.trim()||'';
async function computeProfile(input){const [year,month,day]=input.date.split('-').map(Number),hasTime=Boolean(input.time),hasPlace=Boolean(input.place);let resolvedPlace=null,placeWarning='';if(hasTime&&hasPlace){try{resolvedPlace=await geocodePlace(input.place);}catch(error){placeWarning=error.message||'Lieu non résolu.';}}let sun,moon=null,rising=null,moonLabel='Non calculable sans heure',moonNote='Sans heure de naissance, TADAMB ne fixe pas la Lune.';if(hasTime&&resolvedPlace){const utc=zonedLocalToUtc(input.date,input.time,resolvedPlace.timezone),jd=julianDay(utc);sun=signFromLongitude(sunLongitude(jd));moon=signFromLongitude(moonLongitude(jd));rising=signFromLongitude(ascendantLongitude(jd,resolvedPlace.latitude,resolvedPlace.longitude));moonLabel='—';moonNote='Lune calculée avec le fuseau horaire du lieu résolu.';}else{sun=sunSignFromDate(month,day);if(hasTime){moon=moonSignWithoutTimezone(input.date,input.time);if(moon){moonLabel='—';moonNote='Le signe lunaire reste stable sur l’ensemble des fuseaux plausibles, mais son degré précis n’est pas affiché sans lieu.';}else{moonLabel='Incertaine sans lieu';moonNote='Avec l’heure mais sans fuseau fiable, la Lune peut changer de signe : TADAMB préfère ne pas l’inventer.';}}}const chineseYear=chineseYearProfile(input.date),hourAnimal=hasTime?chineseHourAnimal(input.time):null;let level,meta,intro,note;if(hasTime&&resolvedPlace){level='Portrait complet';meta=`${resolvedPlace.name}${resolvedPlace.country?`, ${resolvedPlace.country}`:''} · ${resolvedPlace.timezone}`;intro='Date, heure et lieu sont disponibles : toutes les couches actuelles du portrait peuvent être croisées.';note='Soleil, Lune, Ascendant, année chinoise, élément, polarité et animal de l’heure sont disponibles. Les calculs astronomiques restent ceux d’un prototype et non d’un éphéméride professionnel.';}else if(hasTime){level='Portrait enrichi';meta=placeWarning?`Lieu non résolu · ${placeWarning}`:'Heure connue · lieu non renseigné';intro='L’heure enrichit la lecture chinoise et, lorsque le signe lunaire reste stable malgré l’absence de fuseau, la lecture émotionnelle.';note=`L’Ascendant reste indisponible sans lieu résolu. ${moonNote}${placeWarning?` ${placeWarning}`:''}`;}else{level='Portrait essentiel';meta='Date de naissance uniquement';intro='Un portrait essentiel construit avec la date de naissance. Les couches dépendant de l’heure ne sont pas inventées.';note='Soleil et profil chinois annuel disponibles. Lune, Ascendant et animal chinois de l’heure restent absents.';}return{input,resolvedPlace,western:{sun,moon,rising},chinese:{year:chineseYear,hourAnimal},precision:{level,meta,intro,note,moonLabel,moonNote,placeWarning}};}
async function onSubmit(event){event.preventDefault();const input={name:value('#firstName'),date:value('#birthDate'),time:value('#birthTime'),place:value('#birthPlace')};if(!input.date){setStatus('La date de naissance est obligatoire.','error');return;}setLoading(true);setStatus('Calcul du portrait…','loading');document.querySelector('#results')?.classList.add('hidden');try{const profile=await computeProfile(input),content=buildContent(profile);state.profile=profile;state.content=content;renderProfile(profile,content);setStatus(profile.precision.placeWarning?'Portrait calculé avec une précision réduite sur le lieu.':'Portrait calculé.','success');window.dispatchEvent(new CustomEvent('tadamb:profile-ready',{detail:{profile,content}}));requestAnimationFrame(()=>document.querySelector('#results')?.scrollIntoView({behavior:'smooth',block:'start'}));}catch(error){console.error('[TADAMB]',error);setStatus(error?.message||'Impossible de calculer le portrait.','error');}finally{setLoading(false);}}
document.addEventListener('DOMContentLoaded',()=>{setupStaticInteractions();setupPdfExport(()=>state);document.querySelector('#birth-form')?.addEventListener('submit',onSubmit,{passive:false});document.querySelector('#firstName')?.addEventListener('input',event=>{const out=document.querySelector('#profileDisplayName');if(out)out.textContent=event.target.value.trim()||'Votre';});});
